[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  port = 8888
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
