name: Update index2_translated.json from CMS

on:
  push:
    paths:
      - 'src/announcements/*.md'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: pip install python-frontmatter

      - name: Run script
        run: python cms-md-to-json.py

      - name: Commit and push
        run: |
          git config --global user.name "netlify-cms-bot"
          git config --global user.email "cms-bot@netlify.dev"
          git add src/script/index2_translated.json
          git commit -m "auto: update translated JSON from CMS .md" || echo "No changes"
          git push
