name: Update index2_translated.json and faq_translated.json from CMS

on:
  push:
    paths:
      - 'src/announcements/*.md'
      - 'src/faq/*.md'
      - 'cms-md-to-json.py'
      - 'cms-faq-to-json.py'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter

      - name: Run ANNUNCI script
        run: python cms-md-to-json.py

      - name: Run FAQ script
        run: python cms-faq-to-json.py

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "netlify-cms-bot"
          git config --global user.email "cms-bot@netlify.dev"
          git pull origin main --rebase || echo "Nothing to pull"
          git add src/script/index2_translated.json
          git add src/script/faq_translated.json
          git commit -m "🔁 auto: update translated JSONs from CMS" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/JAMstackTony/SitoDomus.git main
